### PR TITLE
Add room block to README

### PR DESCRIPTION
**Pull request by alexlehner**
Adding the room block information to the README. This'll make the content live once we merge this pull request. 

Markdown isn't the easiest to read (though slightly better than HTML). You can get a pretty good idea of how this'll look/feel by visiting
https://github.com/alexlehner/alexandsonya.com/tree/roomBlock

Feel free to comment on the formatting or copy. I felt it necessary to update from what Keri sent us.

### CODE REVIEW

**Comment by alexlehner** [comment]
Hey @thekickgalvanic welcome to your first PR review!

**Comment by thekickgalvanic** [comment]
Change requests couched in **, just copy/paste.

**We have two room blocks available for the wedding weekend** at The Renaissance Atlanta Midtown Hotel and The Ellis Hotel.

**If you have any issues with reservations at either hotel**, please reach out to Tess at TOAST Events. Tess@toast-events.com

**Comment by alexlehner** [comment]
@thekickgalvanic, updated. Mind checking again? 

https://github.com/alexlehner/alexandsonya.com/tree/roomBlock should be updated. You can also see exactly what I changed via this link: https://github.com/alexlehner/alexandsonya.com/pull/1/commits/e9bbfe6454c946f6c5e02d9307c2295a55c50e03.

**Comment by thekickgalvanic** [comment]
@alexlehner You're good to commit.

**Pull request merged**
